### PR TITLE
Fix close button

### LINKED ISSUE #144: Fix game never closing when hitting [X] in windowed mode
Fix game never closing when hitting [X] in windowed mode then hitting 'okay' on the close tribal trouble prompt

### PR DESCRIPTION
**Pull request by ryan-linehan**
Fixes an issue where if user triggered quit request from window's [X] or the tray the confirmation modal would be unclickable to finalize quitting the game. Closes #144

### CODE REVIEW

File: server/classes/com/oddlabs/matchserver/discord/DiscordChatroomCoordinator.java [hunk 1]
```diff
@@ -72,7 +72,7 @@ public void sendDiscordMessage(ChatRoom chatRoom, String owner, String msg) {
                     .createMessage(msg)
                     .retry(3)
                     .subscribe(
-                            _ -> {},
+                            unused -> {},
```
Comment (ryan-linehan) [inline server/classes/com/oddlabs/matchserver/discord/DiscordChatroomCoordinator.java:75]: formatter made me rename these

File: server/classes/com/oddlabs/matchserver/discord/DiscordChatroomCoordinator.java [hunk 2]
```diff
@@ -112,7 +112,7 @@ public void sendDiscordEmbed(TextChannel discordChannel, EmbedCreateSpec embed)
                         .createMessage(embed)
                         .retry(3)
                         .subscribe(
-                                _ -> {},
+                                unused -> {},
```
Comment (ryan-linehan) [inline server/classes/com/oddlabs/matchserver/discord/DiscordChatroomCoordinator.java:115]: formatter made me rename this

File: tt/classes/com/oddlabs/tt/render/Renderer.java [hunk 3]
```diff
@@ -292,7 +292,7 @@ private final void run(
         Settings.setSettings(settings);
         File last_event_log_dir = setupBugReporter(deterministic);
 
-        LocalInput _ = new LocalInput();
+        LocalInput localInput = new LocalInput();
```
Comment (ryan-linehan) [inline tt/classes/com/oddlabs/tt/render/Renderer.java:295]: formatter made me rename this

**Review by TimmyTonkaBuilder — APPROVED** [review]
Clean :)
